import{useMemo,useState}from'react';
import{ArrowLeft,BadgeDollarSign,Calculator,Check,ClipboardPaste,Copy,Keyboard,Plus,Trash2}from'lucide-react';
import{contractRouteRows}from'./contractRoutes';

type Leg={id:string;date?:string;flight?:string;origin:string;destination:string;minutes:number|null;factor:number;actual?:number};
type RouteValue=[number,number];
type InputMode='paste'|'manual';
const builtInRoutes=Object.fromEntries(contractRouteRows.trim().split('\n').map(line=>{const[o,d,t,f]=line.trim().split(/\s+/),[h,m]=t.split(':').map(Number);return[`${o}-${d}`,[h*60+m,Number(f)] as RouteValue]}));
const airportNames:Record<string,string>={CTU:'成都双流',TFU:'成都天府',PEK:'北京首都',PKX:'北京大兴',KMG:'昆明',CAN:'广州',SZX:'深圳',CSX:'长沙',WUH:'武汉',XIY:'西安',HGH:'杭州',NKG:'南京',PVG:'上海浦东',SHA:'上海虹桥',TAO:'青岛',XMN:'厦门',FOC:'福州',TNA:'济南',NGB:'宁波',CKG:'重庆',LXA:'拉萨',URC:'乌鲁木齐',HAK:'海口',SYX:'三亚',HKG:'香港'};
const routeKey=(o:string,d:string)=>`${o}-${d}`;
const fmt=(value:number|null)=>value==null?'—':`${Math.floor(Math.round(value)/60)}:${String(Math.round(value)%60).padStart(2,'0')}`;
const money=(value:number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(value);
const parseDuration=(value:string)=>{const match=value.trim().match(/^(\d{1,2}):([0-5]\d)$/);return match?Number(match[1])*60+Number(match[2]):null};
const elapsed=(start:string,end:string)=>{const toMin=(v:string)=>{const[h,m]=v.split(':').map(Number);return h*60+m},a=toMin(start),b=toMin(end);return b>=a?b-a:b+1440-a};

export default function ContractTimeCalculator(){
 const[mode,setMode]=useState<InputMode|null>(null),[raw,setRaw]=useState(''),[legs,setLegs]=useState<Leg[]>([]),[origin,setOrigin]=useState(''),[destination,setDestination]=useState(''),[notice,setNotice]=useState(''),[showPay,setShowPay]=useState(false);
 const[hourlyRate,setHourlyRate]=useState(()=>localStorage.getItem('contract-hourly-rate')||'');
 const[customRoutes,setCustomRoutes]=useState<Record<string,RouteValue>>(()=>{try{return JSON.parse(localStorage.getItem('contract-custom-routes')||'{}')}catch{return{}}});
 const routeValue=(o:string,d:string):RouteValue|[null,number]=>builtInRoutes[routeKey(o,d)]??customRoutes[routeKey(o,d)]??[null,100];
 const makeLeg=(o:string,d:string,extra:Partial<Leg>={}):Leg=>{const[minutes,factor]=routeValue(o,d);return{id:crypto.randomUUID(),origin:o,destination:d,minutes,factor,...extra}};
 const parse=()=>{let date='';const found:Leg[]=[];for(const rawLine of raw.split(/\r?\n/)){const line=rawLine.trim().toUpperCase();if(!line)continue;const dm=line.match(/[【\[]?(\d{4}-\d{1,2}-\d{1,2})[】\]]?/);if(dm&&!/[A-Z]{3}\d{1,2}:\d{2}/.test(line)){date=dm[1];continue}const timed=line.match(/([A-Z]{3})\s*(\d{1,2}:\d{2})\s*[-–—]\s*(\d{1,2}:\d{2})\s*([A-Z]{3})/);if(timed){const flight=(line.match(/\b([A-Z0-9]{2}\d{3,4})\b/)||[])[1]||'';found.push(makeLeg(timed[1],timed[4],{date,flight,actual:elapsed(timed[2],timed[3])}));continue}for(const match of line.matchAll(/\b([A-Z]{3})\s*(?:-|>|→|\s+)\s*([A-Z]{3})\b/g))found.push(makeLeg(match[1],match[2],{date}))}setLegs(found);setNotice(found.length?`已识别 ${found.length} 个航段`:'没有识别到航段，请检查文本格式')};
 const saveCustom=(leg:Leg)=>{if(leg.minutes==null||builtInRoutes[routeKey(leg.origin,leg.destination)])return;const next={...customRoutes,[routeKey(leg.origin,leg.destination)]:[leg.minutes,leg.factor] as RouteValue};setCustomRoutes(next);localStorage.setItem('contract-custom-routes',JSON.stringify(next))};
 const patchLeg=(id:string,patch:Partial<Leg>)=>setLegs(current=>current.map(leg=>{if(leg.id!==id)return leg;const next={...leg,...patch};queueMicrotask(()=>saveCustom(next));return next}));
 const totals=useMemo(()=>legs.reduce((a,l)=>({base:a.base+(l.minutes??0),weighted:a.weighted+(l.minutes??0)*l.factor/100,actual:a.actual+(l.actual??0)}),{base:0,weighted:0,actual:0}),[legs]);
 const rate=Math.max(0,Number(hourlyRate)||0),pay=totals.weighted/60*rate;
 const add=()=>{const o=origin.trim().toUpperCase(),d=destination.trim().toUpperCase();if(!/^[A-Z]{3}$/.test(o)||!/^[A-Z]{3}$/.test(d)){setNotice('请填写两个 3 位机场代码');return}setLegs(v=>[...v,makeLeg(o,d)]);setOrigin('');setDestination('');setNotice(`已添加 ${o} → ${d}`)};
 const copy=async()=>{const detail=legs.map((l,i)=>`${i+1}. ${l.origin}-${l.destination}  承包 ${fmt(l.minutes)}  ${l.factor}%  折算 ${l.minutes==null?'待补充':fmt(l.minutes*l.factor/100)}`);const text=[`承包时间：${fmt(totals.base)}`,`按比例折算：${fmt(totals.weighted)}`,...showPay&&rate?[`预计金额：${money(pay)}（${money(rate)}/小时）`]:[], '',...detail].join('\n');try{await navigator.clipboard.writeText(text);setNotice('计算结果已复制')}catch{setNotice('复制失败，请手动选择结果')}};
 const choose=(next:InputMode)=>{setMode(next);setNotice('');setTimeout(()=>document.querySelector<HTMLElement>('.contract-input textarea,.contract-input input')?.focus(),180)};
 return <div className="contract-tool">
  <section className="contract-hero"><div><span className="tool-kicker"><Calculator/> CONTRACT TIME</span><h2>承包时间计算器</h2><p>{mode?'按步骤完成输入，结果会自动出现在下方。':'先告诉我你想怎样输入航段。'}</p></div>{legs.length>0&&<div className="contract-total result-pop"><small>按比例折算</small><strong>{fmt(totals.weighted)}</strong><span>{legs.length} 个航段</span></div>}</section>
  <nav className="contract-progress" aria-label="计算步骤"><span className="done"><i>1</i>输入方式</span><b/><span className={mode?'active':''}><i>2</i>录入航段</span><b/><span className={legs.length?'active':''}><i>3</i>查看结果</span><b/><span className={legs.length?'active':''}><i>4</i>可选收入</span></nav>
  {!mode?<section className="mode-start"><div className="step-heading"><span>步骤 1</span><h3>你想怎样输入？</h3><p>选择一种方式开始，之后也可以随时切换。</p></div><div className="input-mode-picker"><button onClick={()=>choose('paste')}><span><ClipboardPaste/></span><div><b>粘贴排班</b><small>已有完整排班，一次识别多个航段</small></div><em>推荐</em></button><button onClick={()=>choose('manual')}><span><Keyboard/></span><div><b>手动添加</b><small>没有排班，逐条输入机场三字码</small></div></button></div></section>:<>
   <section className="tool-card contract-input reveal-panel"><div className="step-bar"><div><span>步骤 2</span><h3>{mode==='paste'?'粘贴排班':'手动添加航段'}</h3></div><button className="change-mode" onClick={()=>{setMode(null);setNotice('')}}><ArrowLeft/>更换方式</button></div>{mode==='paste'?<><textarea value={raw} onChange={e=>setRaw(e.target.value)} spellCheck={false} placeholder={'【2026-9-6】\nCA4413/B-6223 CTU10:50-12:20KMG\nCA4414/B-6223 KMG13:25-15:00CTU'}/><p className="input-tip">直接粘贴原始排班，不需要手动整理格式。</p><div className="inline-tool-actions"><button className="primary-btn" disabled={!raw.trim()} onClick={parse}><Calculator/>解析并计算</button><button className="ghost-btn" onClick={()=>setRaw('')}>清空</button></div></>:<><div className="manual-route"><label>出发机场<input maxLength={3} value={origin} onChange={e=>setOrigin(e.target.value.toUpperCase().replace(/[^A-Z]/g,''))} placeholder="CTU"/></label><span>→</span><label>到达机场<input maxLength={3} value={destination} onChange={e=>setDestination(e.target.value.toUpperCase().replace(/[^A-Z]/g,''))} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="KMG"/></label><button className="primary-btn" onClick={add}><Plus/>添加航段</button></div><p className="input-tip">添加后可继续录入下一条，结果会自动累计。</p></>}</section>
   {notice&&<div className="contract-notice"><Check/>{notice}</div>}
   {legs.length>0&&<section className="contract-results reveal-panel"><div className="step-heading compact"><span>步骤 3</span><h3>核对计算结果</h3></div><div className="contract-stats"><article className="main-stat"><span>按比例折算</span><strong>{fmt(totals.weighted)}</strong></article><article><span>表列承包时间</span><strong>{fmt(totals.base)}</strong></article><article><span>排班计划时间</span><strong>{legs.some(x=>x.actual!=null)?fmt(totals.actual):'—'}</strong></article><article><span>航线匹配</span><strong>{legs.filter(x=>x.minutes!=null).length}/{legs.length}</strong></article></div><div className="tool-card contract-detail"><div className="card-title-row"><div><h3>航段明细</h3><p>未收录航线可直接补充，之后会自动记住。</p></div><button className="primary-btn" onClick={copy}><Copy/>复制结果</button></div><div className="contract-table"><div className="contract-row contract-head"><span>日期 / 航班</span><span>航线</span><span>承包</span><span>比例</span><span>折算</span><span/></div>{legs.map(leg=><div className="contract-row" key={leg.id}><span>{[leg.date,leg.flight].filter(Boolean).join(' · ')||'手动'}</span><span><b>{leg.origin} → {leg.destination}</b><small>{airportNames[leg.origin]||leg.origin} → {airportNames[leg.destination]||leg.destination}</small></span><input value={leg.minutes==null?'':fmt(leg.minutes)} placeholder="h:mm" onChange={e=>patchLeg(leg.id,{minutes:parseDuration(e.target.value)})}/><label><input type="number" value={leg.factor} onChange={e=>patchLeg(leg.id,{factor:Math.max(0,Number(e.target.value)||0)})}/><i>%</i></label><strong>{leg.minutes==null?'待补充':fmt(leg.minutes*leg.factor/100)}</strong><button className="icon-btn danger" onClick={()=>setLegs(v=>v.filter(x=>x.id!==leg.id))}><Trash2/></button></div>)}</div></div></section>}
   {legs.length>0&&<section className={'pay-card reveal-panel '+(showPay?'active':'')}><div className="pay-card-icon"><BadgeDollarSign/></div><div className="pay-card-copy"><small>步骤 4 · 可选</small><b>计算预计收入</b><span>按折算后的承包时长计算</span></div><label className="apple-switch"><input aria-label="计算预计收入" type="checkbox" checked={showPay} onChange={e=>setShowPay(e.target.checked)}/><span/></label>{showPay&&<div className="pay-details"><label>每小时费用<div><i>¥</i><input inputMode="decimal" value={hourlyRate} onChange={e=>{const value=e.target.value.replace(/[^\d.]/g,'');setHourlyRate(value);localStorage.setItem('contract-hourly-rate',value)}} placeholder="0.00"/><em>/ 小时</em></div></label><div className="pay-formula"><small>{fmt(totals.weighted)} × {rate?money(rate):'小时费'}</small><strong>{money(pay)}</strong></div></div>}</section>}
  </>}
 </div>;
}
