import type{EnvironmentRule,FlightPhase,FlightSession,PhaseOutput,TrainingSubject}from'./types';
export const phases:FlightPhase[]=[
['external-safety','外部安全检查','外部安全','地面准备'],['cockpit-initial','驾驶舱初始准备','初始准备','地面准备'],['walkaround','外部绕机检查','绕机检查','地面准备'],['cockpit-preparation','驾驶舱准备','驾驶舱准备','地面准备'],['before-start','推出或起动前','起动前','地面准备'],['engine-start','发动机起动','发动机起动','地面准备'],['after-start','起动后','起动后','地面准备'],['taxi','滑行','滑行','地面准备'],['before-takeoff','起飞前','起飞前','起飞'],['takeoff','起飞','起飞','起飞'],['after-takeoff','起飞后','起飞后','起飞'],['climb','爬升','爬升','航路'],['cruise','巡航','巡航','航路'],['descent-preparation','下降准备','下降准备','航路'],['descent','下降','下降','航路'],['approach','进近','进近','进近着陆'],['landing','着陆','着陆','进近着陆'],['go-around','复飞','复飞','进近着陆'],['after-landing','着陆后','着陆后','停机'],['parking','停机','停机','停机'],['securing-aircraft','安全离机','安全离机','停机']].map(([id,name,shortName,group])=>({id,name,shortName,group}as FlightPhase));
export const emptyBaseOutputs:PhaseOutput[]=phases.map(p=>({phaseId:p.id,items:[]}));
const now=()=>new Date().toISOString();
export function newSession():FlightSession{return{id:'current',currentPhaseIndex:0,completedPhaseIds:[],checked:{},environment:{},activeSubjects:[],createdAt:now(),updatedAt:now()}}
export const defaultRules:EnvironmentRule[]=[{id:'rule-high-temperature-template',name:'高温运行（模板）',enabled:false,groups:[{id:'group-high-temp',conditions:[{id:'cond-high-temp',field:'temperature',operator:'gte',value:31}]}],outputs:[{phaseId:'cockpit-preparation',items:[{id:'high-temp-check-template',text:'在此填写高温运行易忘项目',kind:'check',severity:'caution',order:0},{id:'high-temp-risk-template',text:'在此填写高温运行风险提示',kind:'risk',severity:'caution',order:1}]}],updatedAt:now()}];
export const defaultSubjects:TrainingSubject[]=[{id:'subject-dual-fmgc',name:'双 FMGC 失效',aliases:['双飞管失效'],keywords:['FMGC','飞行管理'],description:'',outputs:[],createdAt:now(),updatedAt:now()},{id:'subject-lgciu1-ground',name:'地面 LGCIU 1 失效',aliases:['LGCIU1'],keywords:['起落架控制接口组件','地面'],description:'',outputs:[],createdAt:now(),updatedAt:now()}];
export const fieldLabels:Record<string,string>={airport:'机场',temperature:'气温',windDirection:'风向',windSpeed:'风速',gust:'阵风',visibility:'能见度',runway:'跑道',runwayHeading:'跑道方向',runwayState:'跑道状态',brakingAction:'刹车效应',notes:'备注',crosswind:'侧风分量',headwind:'顶风分量'};
export const operatorLabels:Record<string,string>={gt:'大于',gte:'大于或等于',lt:'小于',lte:'小于或等于',eq:'等于',neq:'不等于',contains:'包含'};
